import { v4 as uuidv4 } from 'uuid';
import { ICategory } from '../interfaces/category';

export const defaultCategories: { [categoriesType: string]: ICategory[] } = {
  debitCategories: [
    {
      id: uuidv4(),
      name: 'Alimentação',
      color: '#1abc9c',
      entryType: 'isDebit',
      order: 0,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Restaurantes e Bares',
      color: '#2ecc71',
      entryType: 'isDebit',
      order: 1,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Casa',
      color: '#3498db',
      entryType: 'isDebit',
      order: 2,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Compras',
      color: '#9b59b6',
      entryType: 'isDebit',
      order: 3,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Cuidados Pessoais',
      color: '#f1c40f',
      entryType: 'isDebit',
      order: 4,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Dívidas e Empréstimos',
      color: '#f39c12',
      entryType: 'isDebit',
      order: 5,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Educação',
      color: '#e67e22',
      entryType: 'isDebit',
      order: 6,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Família e Filhos',
      color: '#d35400',
      entryType: 'isDebit',
      order: 7,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Impostos e Taxas',
      color: '#e74c3c',
      entryType: 'isDebit',
      order: 8,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Investimentos',
      color: '#c0392b',
      entryType: 'isDebit',
      order: 9,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Lazer',
      color: '#ecf0f1',
      entryType: 'isDebit',
      order: 10,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Mercado',
      color: '#bdc3c7',
      entryType: 'isDebit',
      order: 11,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Outras Despesas',
      color: '#95a5a6',
      entryType: 'isDebit',
      order: 12,
      entries: [],
    },
  ],
  creditCategories: [
    {
      id: uuidv4(),
      name: 'Empréstimos',
      color: '#273c75',
      entryType: 'isCredit',
      order: 1,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Investimentos',
      color: '#4cd137',
      entryType: 'isCredit',
      order: 2,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Salário',
      color: '#487eb0',
      entryType: 'isCredit',
      order: 3,
      entries: [],
    },
    {
      id: uuidv4(),
      name: 'Outras Receitas',
      color: '#8c7ae6',
      entryType: 'isCredit',
      order: 4,
      entries: [],
    },
  ],
  initialCategories: [
    {
      id: uuidv4(),
      name: 'Saldo Inicial',
      color: '#27ae60',
      entryType: 'isInit',
      order: 5,
      entries: [],
    },
  ],
};
